### ISSUE TITLE
Repo too big

### ISSUE THREAD

**Issue by alexozer** [alexozer/dotfiles#1]
It appears that some old objects cause a checkout of this repo to occupy over 100M. That's totally unacceptable.

Can probably clean it up with [this](https://github.com/rtyley/bfg-repo-cleaner) and force-push it back.

**Comment by lezed1** [comment]
lol

**Comment by alexozer** [comment]
@lezed1 is that what u used to clean auv repo?

**Comment by lezed1** [comment]
I think I tried it, but the AUV repo is much worse than just extra files tracked at this point

**Comment by lezed1** [comment]
I vaguely remember it being a pain to work with and I didn't use it, but that was a few years ago by now.

**Comment by lezed1** [comment]
Did it work?

**Comment by lezed1** [comment]
Also, why don't you just use NixOS as you main distro :P

**Comment by alexozer** [comment]
@lezed1 Ye I think it worked. Have any ideas for factoring out my screenshots and backgrounds? In time as I change them they'll probably clog up the history again.

I was really torn about NixOS for a while but sadly I just use way too many obscure packages (AUR and such). It took me a while to realize one of Arch's greatest strengths is having the latest version of whatever you want almost always instantly available which is super important for trying new stuff and hacking around. If NixOS package availability at some point rivals the AUR, or it becomes possible to temporarily install from source procedurally (`make install` etc) then maybe it'd finally bop Arch for a personal workstation for me (and maybe our Ubuntu/Docker too).

Regardless, you'd need a dotfiles repo with Nix too.

**Comment by lezed1** [comment]
re: screenshot - git-lfs?

I'm using NixOS for all my stuff currently, and it has more packages than I expected. Also packing anything that's just make is also easier than expected.

**Comment by alexozer** [comment]
@lezed1 that's cool! Do you have a configs repo?

Last time I checked though a few important packages I like weren't very up to date, for example bspwm hasn't been updated in around a year I think.

**Comment by alexozer** [comment]
@lezed1 does NixOS manage your dotfiles somehow?

**Comment by lezed1** [comment]
bspwm is on the latest stable - https://github.com/NixOS/nixpkgs/blob/0653b73bf61f3a23d28c38ab7e9c69a318d433de/pkgs/applications/window-managers/bspwm/default.nix#L7

I don't have it public, but I have a repo that defines each machine. Pretty much all my dotfile-style configs are stored in that repo as well

**Comment by alexozer** [comment]
Hm, maybe I'll have to give it a go again.
